import { Dimensions } from "react-native";
import { StyleSheet } from "react-native";


const Iwidth = Dimensions.get("window").width;
const IHeigth = Dimensions.get("window").height;

export default StyleSheet.create({
  containerImage: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  container: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    // position: "relative",
    borderRadius: 50,
  },
  Line4: {
    position: "absolute",
    top: 677,
    left: 395,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(217,217,217,1)",
    transform: "rotate(-180deg);",
    width: 97,
    height: 1,
  },
  Group948: {
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    top: 82,
    none: "0px",
    width: 391,
    height: 819,
  },
  Frame: {
    width: 26,
    height: 18,
    marginBottom: 24,
  },
  Group134: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  Txt164: {
    fontSize: 48,
    fontFamily: "Jost, sans-serif",
    fontWeight: "600",
    lineHeight: 54,
    color: "rgba(0,0,0,1)",
    width: 391,
    marginBottom: 62,
  },
  Group477: {
    display: "flex",
    flexDirection: "row",
    paddingTop: 17,
    paddingBottom: 17,
    paddingLeft: 26,
    paddingRight: 252,
    marginBottom: 17,
    borderRadius: 15,
    backgroundColor: "rgba(217,217,217,0.5)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,1)",
  },
  Vector: {
    width: 15,
    height: 12,
    marginRight: 24,
  },
  Txt484: {
    fontSize: 15,
    fontFamily: "Montserrat, sans-serif",
    fontWeight: "500",
    color: "rgba(169,169,169,1)",
    textAlign: "center",
    justifyContent: "center",
    width: 49,
    height: 20,
  },

  Group217: {
    display: "flex",
    flexDirection: "row",
    paddingTop: 17,
    paddingBottom: 17,
    paddingLeft: 30,
    paddingRight: 23,
    marginBottom: 58,
    borderRadius: 15,
    backgroundColor: "rgba(217,217,217,0.5)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,1)",
  },
  Frame1: {
    width: 12,
    height: 15,
    marginRight: 22,
  },
  Txt735: {
    fontSize: 15,
    fontFamily: "Montserrat, sans-serif",
    fontWeight: "500",
    color: "rgba(169,169,169,1)",
    textAlign: "center",
    justifyContent: "center",
    width: 81,
    height: 20,
    marginRight: 181,
  },
  Group1: {
    paddingTop: 2,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    backgroundColor: "white",
    /* url(https://firebasestorage.googleapis.com/v0/b/unify-bc2ad.appspot.com/o/vnohg50t4e-30%3A33?alt=media&token=773b37d0-e97b-4b3e-a217-59da52753cfa) */
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgba(169,169,169,1)",
    width: 17,
    height: 14,
  },
  Frame2: {
    width: 17,
    height: 10,
  },

  Group415: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 49,
  },
  Rectangle13: {
    borderWidth: 3,
    borderStyle: "solid",
    borderColor: "rgba(188,0,99,1)",
    width: 18,
    height: 19,
    borderRadius: 6,
    marginRight: 19,
  },
  Txt272: {
    fontSize: 16,
    fontFamily: "Jost, sans-serif",
    fontWeight: "600",
    color: "rgba(188,0,99,1)",
    textAlign: "center",
    justifyContent: "center",
  },

  Group231: {
    paddingTop: 16,
    paddingBottom: 14,
    paddingLeft: 136,
    paddingRight: 134,
    marginBottom: 59,
    borderRadius: 50,
    backgroundColor: "rgba(188,0,99,1)",
    width: 337,
    height: 53,
  },
  Txt247: {
    fontSize: 16,
    // fontFamily: "Montserrat, sans-serif",
    fontWeight: "700",
    color: "rgba(255, 255, 255, 1)",
    textAlign: "center",
    justifyContent: "center",
  },

  Group438: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 36,
  },
  Line3: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(217,217,217,1)",
    transform: "rotate(-180deg);",
    width: 97,
    height: 1,
  },
  Txt439: {
    fontSize: 16,
    // fontFamily: "Jost, sans-serif",
    fontWeight: "600",
    color: "rgba(169,169,169,1)",
    textAlign: "center",
    justifyContent: "center",
  },

  Group075: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 100,
  },
  Group424: {
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 27,
    paddingRight: 26,
    marginRight: 18,
    borderRadius: 15,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,0.2)",
    width: 82,
    height: 53,
  },
  Frame3: {
    width: 27,
    height: 27,
  },

  Group424: {
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 27,
    paddingRight: 26,
    marginRight: 18,
    borderRadius: 15,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,0.2)",
    width: 82,
    height: 53,
  },
  Frame3: {
    width: 27,
    height: 27,
  },

  Group153: {
    paddingTop: 9,
    paddingBottom: 10,
    paddingLeft: 27,
    paddingRight: 26,
    borderRadius: 15,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,0.2)",
    width: 82,
    height: 53,
  },
  Frame4: {
    width: 27,
    height: 32.08,
  },

  Group254: {
    display: "flex",
    flexDirection: "row",
  },
  Txt246: {
    fontSize: 16,
    // fontFamily: "Montserrat, sans-serif",
    fontWeight: "400",
    color: "rgba(156,148,148,1)",
    textAlign: "center",
    justifyContent: "center",
    marginRight: 7,
  },
  Txt143: {
    fontSize: 16,
    // fontFamily: "Montserrat, sans-serif",
    fontWeight: "700",
    color: "rgba(188,0,99,1)",
    textAlign: "center",
    justifyContent: "center",
  },
});
