import { Dimensions } from 'react-native';
import { StyleSheet } from 'react-native';

const Iwidth = Dimensions.get('window').width / 2;


export default StyleSheet.create({
    containerImage: {
        alignItems: 'center',
        justifyContent: 'center',
        width: Iwidth,
        height: Iwidth,
    },
    container: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        position: "relative",
        borderRadius: 50,
        width: Iwidth,
        height: Iwidth,
      },
      Group178: {
        display: "flex",
        flexDirection: "column",
      },
      Frame: {
        width: 26,
        height: 18,
        marginBottom: 47,
      },
      Group927: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
      },
      Txt435: {
        fontSize: 48,
        fontFamily: "Jost, sans-serif",
        fontWeight: "600",
        color: "rgba(0,0,0,1)",
        textAlign: "center",
        justifyContent: "center",
        width: 391,
        height: 96,
        marginBottom: 72,
      },
      Group122: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 29,
        paddingRight: 63,
        marginBottom: 17,
        borderRadius: 15,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "rgba(0,0,0,1)",
      },
      Frame1: {
        width: 27,
        height: 27,
        marginRight: 22,
      },
      Txt976: {
        fontSize: 14,
        fontFamily: "Poppins, sans-serif",
        fontWeight: "600",
        color: "rgba(0,0,0,1)",
        textAlign: "center",
        justifyContent: "center",
        width: 194,
        height: 24,
      },
    
      Group588: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 25,
        paddingRight: 64,
        marginBottom: 17,
        borderRadius: 15,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "rgba(0,0,0,1)",
      },
      Frame2: {
        width: 27,
        height: 27,
        marginRight: 25,
      },
      Txt976: {
        fontSize: 14,
        fontFamily: "Poppins, sans-serif",
        fontWeight: "600",
        color: "rgba(0,0,0,1)",
        textAlign: "center",
        justifyContent: "center",
        width: 194,
        height: 24,
      },
    
      Group465: {
        display: "flex",
        flexDirection: "row",
        paddingTop: 9,
        paddingBottom: 10,
        paddingLeft: 26,
        paddingRight: 64,
        marginBottom: 100,
        borderRadius: 15,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "rgba(0,0,0,1)",
      },
      Frame3: {
        width: 27,
        height: 32.08,
        marginRight: 24,
      },
      Txt976: {
        fontSize: 14,
        fontFamily: "Poppins, sans-serif",
        fontWeight: "600",
        color: "rgba(0,0,0,1)",
        textAlign: "center",
        justifyContent: "center",
        width: 194,
        height: 24,
      },
    
      Group216: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 94,
      },
      Line1: {
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "rgba(217,217,217,1)",
        width: 124,
        height: 1,
        marginRight: 21,
      },
      Txt253: {
        fontSize: 16,
        fontFamily: "Montserrat, sans-serif",
        fontWeight: "700",
        color: "rgba(188,0,99,1)",
        textAlign: "center",
        justifyContent: "center",
        marginRight: 14,
      },
      Line2: {
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "rgba(217,217,217,1)",
        width: 124,
        height: 1,
      },
    
      Group865: {
        paddingTop: 16,
        paddingBottom: 14,
        paddingLeft: 75,
        paddingRight: 73,
        marginBottom: 104,
        borderRadius: 50,
        backgroundColor: "rgba(188,0,99,1)",
        width: 337,
        height: 53,
      },
      Txt124: {
        fontSize: 16,
        fontFamily: "Montserrat, sans-serif",
        fontWeight: "700",
        color: "rgba(255, 255, 255, 1)",
        textAlign: "center",
        justifyContent: "center",
      },
    
      Group7310: {
        display: "flex",
        flexDirection: "row",
      },
      Txt883: {
        fontSize: 16,
        fontFamily: "Montserrat, sans-serif",
        fontWeight: "400",
        color: "rgba(156,148,148,1)",
        textAlign: "center",
        justifyContent: "center",
        marginRight: 12,
      },
      Txt752: {
        fontSize: 16,
        fontFamily: "Montserrat, sans-serif",
        fontWeight: "700",
        color: "rgba(188,0,99,1)",
        textAlign: "center",
        justifyContent: "center",
      },
})